name: amfosstask_6
description: A new Flutter project.
publish_to: 'none' 
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^2.1.0
  dots_indicator: ^2.0.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

  